app:
  time:
    limit-ms:

error:
  logging:
    kafka:
      enabled:
      bootstrap-servers:
      topic:
      producer:
        retries:
        acks:
    db:
      enabled:
      schema-validation:
      auto-create-tables:


